### ISSUE TITLE
Domain fetch failures

### ISSUE THREAD

**Issue by michalschott** [michimani/goacm#1]
https://github.com/michimani/goacm/blob/main/goacm.go#L195-L200

Assuming I have two domains of the same name, one is public other one is private - above bit of code fails.

Propose to add filtering based on public domains only, otherwise DNS verification record might be added to private one and ACM certificate will fail to gets validation done.

**Comment by michimani** [comment]
@michalschott  
Thank you for pointing it out!  
I couldn't consider the possibility of that situation. As you pointed out, I would like to modify it to cover only the public domain.    
Please wait for a while until the correction is completed.

**Comment by michimani** [comment]
@michalschott  
I have released v0.3.3 as a version that fixes the issues you pointed out.
Thanks for your suggestions!

**Comment by michalschott** [comment]
Can confirm this works now as expected, thanks @michimani
